name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Permite solicitar o JWT do GitHub para autenticação com a AWS
  contents: read    # Necessário para actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050139769:role/role-para-criacao-role-pode-ser-apagada
          aws-region: sa-east-1
          audience: sts.amazonaws.com   # Assegure que o audience está configurado corretamente

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
