name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Permite solicitar o JWT do GitHub para autenticação com a AWS
  contents: read    # Necessário para actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Terraform
        run: |
          # Baixar e instalar Terraform
          wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
          sudo apt-get install unzip
          unzip terraform_1.6.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050139769:role/role-para-criacao-role-pode-ser-apagada
          aws-region: sa-east-1
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
